- name: Create flavors
  os_nova_flavor:
    cloud: admin
    state: present
    flavorid: '{{ item.flavorid }}'
    name: '{{ item.name }}'
    ram: '{{ item.ram }}'
    vcpus: '{{ item.vcpus }}'
    disk: '{{ item.disk }}'
  loop:
    - {flavorid: '0', name: 'm1.nano',   vcpus: 1, disk:   1, ram:    64}
    - {flavorid: '1', name: 'm1.tiny',   vcpus: 1, disk:   1, ram:   512}
    - {flavorid: '2', name: 'm1.small',  vcpus: 1, disk:  80, ram:  2048}
    - {flavorid: '3', name: 'm1.medium', vcpus: 2, disk:  80, ram:  4096}
    - {flavorid: '4', name: 'm1.large',  vcpus: 4, disk:  80, ram:  8192}
    - {flavorid: '5', name: 'm1.xlarge', vcpus: 8, disk: 160, ram: 16384}
    - {flavorid: '6', name: 'm2.large',  vcpus: 2, disk:  80, ram:  8192}

