- name: Add authorized_key
  vars:
    user: "masayuki"
    keys:
      - ed25519
      - rsa
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '/home/{{user}}/.ssh/id_{{item}}.pub')}}"
  with_items:
    - "{{ keys }}"
- name: Update all package
  zypper:
    name: '*'
    state: latest
  become: yes