#########################
# etcd
#########################
- name: Add etcd group
  group: name=etcd system=yes
  become: yes
- name: Add etcd user
  user:
    name: etcd
    system: yes
    home: /var/lib/etcd
    shell: /bin/false
    group: etcd
  become: yes
- name: Make directories
  file:
    path: '{{ item }}'
    owner: etcd
    group: etcd
    state: directory
  with_items:
    - /etc/etcd
    - /var/lib/etcd
  become: yes
- name: Check etcd binary existence
  stat:
    path: /usr/bin/etcdctl
  register: etcdctl
- name: Install etcd
  script: files/install_etcd.sh
  when: not etcdctl.stat.exists
  become: yes
- name: Create etcd.conf.yml and etcd.service
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '0644'
  with_items:
    - {src: 'etcd.conf.yml.j2', dest: '/etc/etcd/etcd.conf.yml', owner: 'etcd', group: 'etcd'}
    - {src: 'etcd.service.j2', dest: '/usr/lib/systemd/system/etcd.service', owner: 'root', group: 'root'}
  become: yes
- name: Reload and restart etcd
  systemd:
    name: etcd.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
