- name: Create security group rule for ping
  os_security_group_rule:
    cloud: demo
    security_group: default
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
- name: Create security group rule for ssh
  os_security_group_rule:
    cloud: demo
    security_group: default
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
