---
- hosts: all
  become: yes
  tasks:
    - name: Install docker
      zypper:
        name: ['docker','python3-docker','python2-docker']
        state: present
    - name: Start docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
        enabled: yes
    - name: Run prometheus/node_exporter
      docker_container:
        name: node_exporter
        ports:
          - '9100:9100'
        restart_policy: always
        image: prom/node-exporter

