- name: Install opnestack packages
  zypper:
    name: ['python-openstackclient','mariadb','mariadb-client','python-PyMySQL']
    state: present
  become: yes
- name: Configure mysql
  template:
    src: openstack.cnf.j2
    dest: /etc/my.cnf.d/openstack.cnf
    owner: root
    group: root
    mode: "0644"
  become: yes
