#########################
# Memcached
#########################
- name: Install memcached
  zypper:
    name: ['memcached','python-python-memcached']
    state: present
  become: yes
- name: Configure memcached
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: "0644"
    backup: yes
  become: yes
- name: restart memcached service
  systemd:
    name: memcached.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
