- name: Get Images
  get_url:
    url: '{{ item.url }}'
    dest: '/tmp/{{ item.file }}'
  loop:
    - {url: 'http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img', file: 'cirros-0.4.0-x86_64-disk.img'}
    - {url: 'http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2', file: 'CentOS-6-x86_64-GenericCloud.qcow2'}
    - {url: 'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2', file: 'CentOS-7-x86_64-GenericCloud.qcow2'}
    - {url: 'https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2', file: 'debian-9-openstack-amd64.qcow2'}
    - {url: 'https://download.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2', file: 'Fedora-Cloud-Base-29-1.2.x86_64.qcow2'}
    - {url: 'http://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.0/images/openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.113.qcow2', file: 'openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.113.qcow2'}
- name: Image upload
  os_image:
    cloud: admin
    name: '{{ item.name }}'
    container_format: bare
    disk_format: qcow2
    state: present
    filename: '/tmp/{{ item.file }}'
    is_public: yes
  loop:
    - {name: 'cirros', file: 'cirros-0.4.0-x86_64-disk.img'}
    - {name: 'centos6', file: 'CentOS-6-x86_64-GenericCloud.qcow2'}
    - {name: 'centos7', file: 'CentOS-7-x86_64-GenericCloud.qcow2'}
    - {name: 'debian9', file: 'debian-9-openstack-amd64.qcow2'}
    - {name: 'fedora29', file: 'Fedora-Cloud-Base-29-1.2.x86_64.qcow2'}
    - {name: 'opensuse-leap15', file: 'openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.113.qcow2'}

