- name: Get Images
  get_url:
    url: '{{ item.url }}'
    dest: '/tmp/{{ item.file }}'
  loop:
    - {url: 'http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img', file: 'cirros-0.4.0-x86_64-disk.img'}
    - {url: 'http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2', file: 'CentOS-6-x86_64-GenericCloud.qcow2'}
    - {url: 'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2', file: 'CentOS-7-x86_64-GenericCloud.qcow2'}
    - {url: 'https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2', file: 'debian-9-openstack-amd64.qcow2'}
    - {url: 'https://download.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2', file: 'Fedora-Cloud-Base-29-1.2.x86_64.qcow2'}
    - {url: 'https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img', file: 'boinic-server-cloudimg-amd64.img'}
    - {url: 'https://cloud-images.ubuntu.com/disco/current/disco-server-cloudimg-amd64.img', file: 'disco-server-cloudimg-amd64.img'}
    - {url: 'http://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.0/images/openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.136.qcow2', file: 'openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.136.qcow2'}

- name: Get Kubic Images
  vars:
    kubic_base_url: https://download.opensuse.org/repositories/devel:/kubic:/images/openSUSE_Tumbleweed/
    image_download_dest_dir: /tmp/
  get_url:
    url: '{{ kubic_base_url }}{{ item.filename }}'
    dest: '/tmp/{{ item.filename }}'
    # sha256sum: '{{ item.sha256sum }}'
    #force: True
  loop:
    # Skip this image since the kubeadm-cri-o-*-Build23.4 image is corrupt now.
    #- {filename: 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-kubeadm-cri-o-OpenStack-Cloud-Build23.4.qcow2.xz',
    #    sha256sum: 'd96b0df639ef19cc4205f66634ccea94560f2ba1ccdcefd45f5449e574dec7bc'}
    - {filename: 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-MicroOS-podman-OpenStack-Cloud-Build23.4.qcow2.xz',
        sha256sum: 'f9b53fccc6b0473784182569e30c38bf8ed2ed02afe579a80ab0390bfaa04ec7'}

- name: Image extract
  command: unxz '/tmp/{{ item }}'
  loop:
    #- 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-kubeadm-cri-o-OpenStack-Cloud-Build23.4.qcow2.xz'
    - 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-MicroOS-podman-OpenStack-Cloud-Build23.4.qcow2.xz'
- name: Image upload
  os_image:
    cloud: admin
    name: '{{ item.name }}'
    container_format: bare
    disk_format: qcow2
    state: present
    filename: '/tmp/{{ item.file }}'
    is_public: yes
  loop:
    - {name: 'cirros', file: 'cirros-0.4.0-x86_64-disk.img'}
    - {name: 'centos6', file: 'CentOS-6-x86_64-GenericCloud.qcow2'}
    - {name: 'centos7', file: 'CentOS-7-x86_64-GenericCloud.qcow2'}
    - {name: 'debian9', file: 'debian-9-openstack-amd64.qcow2'}
    - {name: 'fedora29', file: 'Fedora-Cloud-Base-29-1.2.x86_64.qcow2'}
    - {name: 'ubuntu-boinic', file: 'boinic-server-cloudimg-amd64.img'}
    - {name: 'ubuntu-disco', file: 'disco-server-cloudimg-amd64.img'}
    - {name: 'opensuse-leap15', file: 'openSUSE-Leap-15.0-OpenStack.x86_64-0.0.4-Buildlp150.12.136.qcow2'}
    #- {name: 'kubic-kubeadm-cri-o', file: 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-kubeadm-cri-o-OpenStack-Cloud-Build23.4.qcow2'}
    - {name: 'kubic-microos', file: 'openSUSE-Tumbleweed-Kubic.x86_64-15.0-MicroOS-podman-OpenStack-Cloud-Build23.4.qcow2'}

